### PR TITLE
Misc clippy fixes

### PR DESCRIPTION
**Pull request by xangelix**
Requires: https://github.com/zakarumych/egui-snarl/pull/46 (as this includes clippy fixes to hit crate level clippy restrictions).

A significant amount of clippy fixes to deal with almost all the warnings (at the pedantic level).

Feel free to accept only a portion of this if you don't like the Self references for example. I think the rest of the changes look good. :)

### CODE REVIEW

**Review by zakarumych — APPROVED** [review]
Thank you!

I'll merge this once egui-probe 0.7 is released

**Comment by xangelix** [comment]
Thanks!

I went ahead and allows clippy::use_self in both the crate, and the demo. https://github.com/zakarumych/egui-snarl/pull/47/commits/008a7d9c4ec46113b6721362ce43607f1b80edd2 https://github.com/zakarumych/egui-snarl/pull/47/commits/50634e558ab8022e16a29bada7ce280368d311fa

I undid the use of `Self` in value positions (outside of this PR), please confirm this is correct! https://github.com/zakarumych/egui-snarl/pull/47/commits/fa5fde73e499a32ed2e8912e66df838074b5d29a

**Comment by xangelix** [comment]
Reverted all changes related to clippy::use_self.

**Comment by zakarumych** [comment]
This got conflicts after merge of your other PR

**Pull request merged**
